### ISSUE TITLE
[Question] Different lightness curves for grey and color scales

### ISSUE THREAD

**Issue by GeeWizWow** [adobe/leonardo#165]
Hey, I've just spent some time reading over @NateBaldwinDesign awesome articles, as well as the [spectrum documentation](https://spectrum.adobe.com/page/color-system/), and if you don't mind, I have some questions about putting it into practice using Leonardo

---

My understanding is that you guys are generating your **grey** color palette using a range of 11 target contrasts starting from **grey-100**, e.g. `grey-100 => 1:1`. And then further generating 14 tints and shades for colors using target contrasts against the previously selected **grey-100**.

Is that correct? As it doesn't seem to be possible to achieve using the leonardo UI, where one would need to be able to create a specific lightness/ contrast curve for the Grey background scale, and a second for the color scales.

Interestingly, the `demo.html` file does illustrate using different curves for grey and colors, but as a tool it's not as open to sharing or iteration.

---

Separately I have a question about Key colors, if hypothetically I have a static blue traditionally used by my brand, would this be a good value to specify when creating a Blue scale?

**Comment by NateBaldwinDesign** [comment]
Hi @GeeWizWow sorry for the delay! Yes, that is correct. More work needs to be done in order to solve for the user experience in supporting multiple unique target contrast ratios in the Leonardo UI. With the latest refactor, it was simplified for the most common use-case, as we see most design systems have a single scale that is used for all colors. However, in the npm module, you can use completely unique target ratios for any and all colors, since they are parameterized individually.

The demo code helps to illustrate how an adaptive theme it is achieved using Leonardo & css properties.

As for key colors, a brand blue _can_ be a very good color to use for your blues. But it really depends on your brand identity, and the goals/challenges you have designing the interface. Some blues may not work as well within UI as others (for example, highly saturated blues or very desaturated blues).
