### ISSUE TITLE
Slow color update

### ISSUE THREAD

**Issue by fnky** [adobe/leonardo#23]
## Description

Using the macOS Color Picker, when using a slider it will change the color on each movement. The app tries to update the browser URL, which causes the app to slow down until the last change is applied.

## Steps to reproduce

1. Go to http://leonardocolor.io/
2. Click on a color to open the color picker
3. Use the slider to change the color hue (or other sliders) rapidly.
4. See the update being applied for each change and slow down the browser.

## Expected behavior

When changing a color, it should update the preview in real-time but only update the URL after a certain time to avoid the app from slowing down/freezing upon changing colors.

## Screenshots

![2019-12-11 16 15 18](https://user-images.githubusercontent.com/995050/70634058-da51f180-1c31-11ea-9a6e-8ac7a5c4628f.gif)

## Environment
 - **Browser(s) and OS(s):** Chrome 78.0.3904.108 on macOS Mojave (10.14.5)

**Comment by sam-cross** [comment]
Shouldn't it just update when the mouse button is released? That would make more sense and stop this behaviour. Unfortunately in that case you may lose live preview, but that could be reimplemented by grabbing the current colour through the app rather than by grabbing it from the uelt.

**Comment by fnky** [comment]
I don't know how the app currently syncs with URL. If uses the URL as the source of state then it would have to be changed to use an object instead and update the URL based on updates to that object.

It could still read from the URL on initial load and populate the object based on the URL.

**Comment by sam-cross** [comment]
@fnky that's what I'm thinking. That would be a nicer solution

**Comment by NateBaldwinDesign** [comment]
The way it's currently working is this:
1. On page load, URL is parsed for parameters
2. UI setup -> For each param, color inputs (with values) & ratio inputs (with values) are added to the UI, and options are set for colorspace interpolation.
3. Once UI is setup per existing parameters, `colorInput()` function is fired, which creates the color scale, color data and the charts & model, and runs the `generateContrastColors()` function.
4. *at the end of the `colorInput()` function, `updateParams()` is fired* - this is likely the cause of the issue. 

The reason for it's placement at the end of `colorInput` is to update the params printed in the URL so that upon refresh or copying of the URL, the colors and params are up-to-date. 

I would still want `colorInput()` to be run onInput for colorInputs, ratioInputs, and base color inputs, for live reloading. *However*, it may be worth separating the `updateParams()` function from the `colorInput()` function. Debouncing and separating from being called _inside_ of the `colorInput()` function may be a better solution. 

If this can't be resolved, it may also be worth pulling it out and having a separate button in the UI to "Save", which would print the new params in the URL. This would give the user the ability to make modifications within the tool without losing a previous state.

**Comment by sam-cross** [comment]
Can't the URL only be updated when the mouse button is released?

**Comment by NateBaldwinDesign** [comment]
That would be better to do, that way the colors can still change on input. URL param updates aren’t necessary until user makes gesture implying decisive action such as mouse up.

**Comment by georapbox** [comment]
The issue does not seem to be the `updateParams()` function. It's the `colorInput()` that is invoked many times on color change event and this is the one that causes the page to be laggy by blocking the main thread. I also did a test by totally removing the `updateParams()` invocation and the result was the same. The reason that the URL parameters seem to update in this way is the result rather than the cause. When doing heavy calculations in an event handler is always a good practice to throttle or debounce depending on the case. In this case, if you want the user to see the color updates as real time as possible, I think that throttling the event handler is preferable to debouncing. But this is my opinion of course. :)

**Comment by fnky** [comment]
> Can't the URL only be updated when the mouse button is released?

This depends on whether the browser provides this event based on the interaction with the native UI (the current color picker is native, not built-in).

Both event listeners for `change` and `input` will be called when the color changes and the event is emitted from the native color UI and proxied through the browser to JS.

I don't think there's a way to listen for when the color change happens on mouse release, unfortunately.

So to support this, it would either require a custom color picker or using a state object that is updated (faster) and debounced to update the URL if changes haven't been made within a certain amount of time (say 500ms).

**Comment by georapbox** [comment]
![Dec-13-2019 12-17-51](https://user-images.githubusercontent.com/6596039/70792806-ae09b280-1da2-11ea-9c79-8e983284279e.gif)
This is how it works if event handlers are throttled.

**Comment by fnky** [comment]
[Here's an example using debounce](https://codepen.io/cbp/pen/4cc30633b7438e851c5a363028a3486c)

Notice that it doesn't update the URL more than needed within given timeout (150ms in this case, could be more or less).

Also this demo shows that the updating UI and query can be separated, so that colors change in real-time whereas URL is updated to latest value after some time.

**Comment by georapbox** [comment]
The point I was trying to make is that it is not the `updateParams` invocation that causes the UI to be unresponsive. It's all the logic that is included inside the `colorInput` function. 

@fnky your demo makes sense but in this case even if we debounce the `updateParams` the rest of the `colorInput` functions still does heavy calculations. The best solution would be to break the `colorInput` into more functions and only debounce the parts that are not required for the UI to update. This, though, would require some kind of refactor.

The proposed solution of throttling the event handler seemed to me as the one with the less effort at the time being so that the app's UI is not blocked.
